/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArenaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_CONSENSUS_PERCENT"
      | "VALIDATION_DEADLINE"
      | "VALIDATION_FEE_PERCENT"
      | "challengeCount"
      | "challengeWinners"
      | "challenges"
      | "createChallenge"
      | "enterChallenge"
      | "getChallenge"
      | "getSubmission"
      | "owner"
      | "renounceOwnership"
      | "resolveChallenge"
      | "submitProof"
      | "transferOwnership"
      | "validatorRegistry"
      | "vote"
      | "votes"
      | "wodToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChallengeCreated"
      | "ChallengeEntered"
      | "ChallengeResolved"
      | "OwnershipTransferred"
      | "SubmissionSubmitted"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_CONSENSUS_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATION_DEADLINE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATION_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengeWinners",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challenges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createChallenge",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enterChallenge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChallenge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveChallenge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "votes", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "wodToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MIN_CONSENSUS_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATION_DEADLINE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATION_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "challenges", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wodToken", data: BytesLike): Result;
}

export namespace ChallengeCreatedEvent {
  export type InputTuple = [
    challengeId: BigNumberish,
    name: string,
    entryFee: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    challengeId: bigint,
    name: string,
    entryFee: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    challengeId: bigint;
    name: string;
    entryFee: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChallengeEnteredEvent {
  export type InputTuple = [
    challengeId: BigNumberish,
    athlete: AddressLike,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [
    challengeId: bigint,
    athlete: string,
    entryFee: bigint
  ];
  export interface OutputObject {
    challengeId: bigint;
    athlete: string;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChallengeResolvedEvent {
  export type InputTuple = [
    challengeId: BigNumberish,
    winners: AddressLike[],
    totalPrizePool: BigNumberish
  ];
  export type OutputTuple = [
    challengeId: bigint,
    winners: string[],
    totalPrizePool: bigint
  ];
  export interface OutputObject {
    challengeId: bigint;
    winners: string[];
    totalPrizePool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionSubmittedEvent {
  export type InputTuple = [
    challengeId: BigNumberish,
    athlete: AddressLike,
    proofCID: string
  ];
  export type OutputTuple = [
    challengeId: bigint,
    athlete: string,
    proofCID: string
  ];
  export interface OutputObject {
    challengeId: bigint;
    athlete: string;
    proofCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    challengeId: BigNumberish,
    validator: AddressLike,
    athlete: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    challengeId: bigint,
    validator: string,
    athlete: string,
    approved: boolean
  ];
  export interface OutputObject {
    challengeId: bigint;
    validator: string;
    athlete: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Arena extends BaseContract {
  connect(runner?: ContractRunner | null): Arena;
  waitForDeployment(): Promise<this>;

  interface: ArenaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_CONSENSUS_PERCENT: TypedContractMethod<[], [bigint], "view">;

  VALIDATION_DEADLINE: TypedContractMethod<[], [bigint], "view">;

  VALIDATION_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  challengeCount: TypedContractMethod<[], [bigint], "view">;

  challengeWinners: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  challenges: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        name: string;
        description: string;
        entryFee: bigint;
        prizePool: bigint;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  createChallenge: TypedContractMethod<
    [
      name: string,
      description: string,
      entryFee: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  enterChallenge: TypedContractMethod<
    [challengeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getChallenge: TypedContractMethod<
    [challengeId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        name: string;
        description: string;
        entryFee: bigint;
        prizePool: bigint;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
        participantCount: bigint;
      }
    ],
    "view"
  >;

  getSubmission: TypedContractMethod<
    [challengeId: BigNumberish, athlete: AddressLike],
    [
      [string, string, bigint, boolean, bigint, bigint] & {
        athleteAddress: string;
        proofCID: string;
        timestamp: bigint;
        exists: boolean;
        approvalVotes: bigint;
        rejectVotes: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveChallenge: TypedContractMethod<
    [challengeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [challengeId: BigNumberish, proofCID: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validatorRegistry: TypedContractMethod<[], [string], "view">;

  vote: TypedContractMethod<
    [challengeId: BigNumberish, athlete: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  votes: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, boolean, bigint] & {
        validator: string;
        athlete: string;
        approved: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  wodToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_CONSENSUS_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VALIDATION_DEADLINE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VALIDATION_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengeWinners"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "challenges"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        name: string;
        description: string;
        entryFee: bigint;
        prizePool: bigint;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createChallenge"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      entryFee: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterChallenge"
  ): TypedContractMethod<[challengeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getChallenge"
  ): TypedContractMethod<
    [challengeId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        name: string;
        description: string;
        entryFee: bigint;
        prizePool: bigint;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
        participantCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [challengeId: BigNumberish, athlete: AddressLike],
    [
      [string, string, bigint, boolean, bigint, bigint] & {
        athleteAddress: string;
        proofCID: string;
        timestamp: bigint;
        exists: boolean;
        approvalVotes: bigint;
        rejectVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveChallenge"
  ): TypedContractMethod<[challengeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [challengeId: BigNumberish, proofCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validatorRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [challengeId: BigNumberish, athlete: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, boolean, bigint] & {
        validator: string;
        athlete: string;
        approved: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "wodToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ChallengeCreated"
  ): TypedContractEvent<
    ChallengeCreatedEvent.InputTuple,
    ChallengeCreatedEvent.OutputTuple,
    ChallengeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ChallengeEntered"
  ): TypedContractEvent<
    ChallengeEnteredEvent.InputTuple,
    ChallengeEnteredEvent.OutputTuple,
    ChallengeEnteredEvent.OutputObject
  >;
  getEvent(
    key: "ChallengeResolved"
  ): TypedContractEvent<
    ChallengeResolvedEvent.InputTuple,
    ChallengeResolvedEvent.OutputTuple,
    ChallengeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionSubmitted"
  ): TypedContractEvent<
    SubmissionSubmittedEvent.InputTuple,
    SubmissionSubmittedEvent.OutputTuple,
    SubmissionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ChallengeCreated(uint256,string,uint256,uint256,uint256)": TypedContractEvent<
      ChallengeCreatedEvent.InputTuple,
      ChallengeCreatedEvent.OutputTuple,
      ChallengeCreatedEvent.OutputObject
    >;
    ChallengeCreated: TypedContractEvent<
      ChallengeCreatedEvent.InputTuple,
      ChallengeCreatedEvent.OutputTuple,
      ChallengeCreatedEvent.OutputObject
    >;

    "ChallengeEntered(uint256,address,uint256)": TypedContractEvent<
      ChallengeEnteredEvent.InputTuple,
      ChallengeEnteredEvent.OutputTuple,
      ChallengeEnteredEvent.OutputObject
    >;
    ChallengeEntered: TypedContractEvent<
      ChallengeEnteredEvent.InputTuple,
      ChallengeEnteredEvent.OutputTuple,
      ChallengeEnteredEvent.OutputObject
    >;

    "ChallengeResolved(uint256,address[],uint256)": TypedContractEvent<
      ChallengeResolvedEvent.InputTuple,
      ChallengeResolvedEvent.OutputTuple,
      ChallengeResolvedEvent.OutputObject
    >;
    ChallengeResolved: TypedContractEvent<
      ChallengeResolvedEvent.InputTuple,
      ChallengeResolvedEvent.OutputTuple,
      ChallengeResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SubmissionSubmitted(uint256,address,string)": TypedContractEvent<
      SubmissionSubmittedEvent.InputTuple,
      SubmissionSubmittedEvent.OutputTuple,
      SubmissionSubmittedEvent.OutputObject
    >;
    SubmissionSubmitted: TypedContractEvent<
      SubmissionSubmittedEvent.InputTuple,
      SubmissionSubmittedEvent.OutputTuple,
      SubmissionSubmittedEvent.OutputObject
    >;

    "VoteCast(uint256,address,address,bool)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
